# fly.toml app configuration file generated for blog-ancient-thunder-4378 on 2025-01-21T20:37:44-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'blog-ancient-thunder-4378'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3003
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
