###POST
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Test Blog",
  "author": "Test Author",
  "url": "https://testblog.com",
  "likes": 10
}

###GET ALL
GET http://localhost:3003/api/blogs